---
version: 2
plan:
  project-key: AGSAFARI
  key: IVSPECS
  name: Increment version
variables:
  dockerNode: node:15.14.0-buster-slim

stages:
  - Increment:
      manual: false
      final: false
      jobs:
        - Increment

Increment:
  key: INCR
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.YARN_DIR}: "${bamboo.cacheYarn}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            bash ./Scripts/increment-version.sh
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: 'skip ci: Automatic increment version'
          selectedRepository: defaultRepository
  requirements:
    - adg-docker: 'true'

triggers: []
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
