---
version: 2
plan:
  project-key: AGSAFARI
  key: IVBNSPECS
  name: Increment build number
stages:
  - Increment:
      manual: false
      final: false
      jobs:
        - Increment

Increment:
  key: INCR
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            bash ./Scripts/increment-build-number.sh
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: 'skip ci: Automatic increment build number'
          selectedRepository: defaultRepository
  requirements:
    - adg-docker: 'true'
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
